静态文件支持
guqing/halo-plugin-experimental pull request #1
Opened 2022-01-12 15:36 UTC by cooker

2022-01-13 02:25 UTC, guqing commented
hi @cooker 感谢你对此提交PR，不过为了方便你应该在描述中说明该如何测试它

2022-01-21 06:10 UTC, guqing commented
@cooker 非常感谢你的贡献，不过我测试的过程中功能上还有些小问题，比如我访问http://localhost:8090/plugins/web/potatoes/abc/ 时 报错会提示 NOT FOUND potatoes/abc/.ftl 或许带/应该访问的是potatoes/abc/index.ftl

2022-01-21 08:28 UTC, guqing requested changes

2022-01-21 08:28 UTC, guqing commented on core/src/test/java/run/halo/app/FileViewerTest.java
> +//        String file = "F:\\IT\\Code\\halo-plugin-experimental\\build\\plugins\\plugin-potatoes-1.0-SNAPSHOT.zip";
@cooker 这个测试文件只能运行在windows机器上而无法运行在ci或我的linux 可以将绝对路径改为相对路径或通过Files创建临时目录来编写

2022-01-21 08:28 UTC, guqing commented on plugins/potatoes/build.gradle
> +//    include '*/*'
@cooker 这些不需要的注释需要删一下

2022-01-21 08:28 UTC, guqing commented on plugins/potatoes/src/main/resources/static/abc/index.ftl
> +</html>
@cooker 行末需要一个空行

2022-01-21 08:28 UTC, guqing commented on plugins/potatoes/src/main/resources/static/index.ftl
> +</html>
@cooker 同上

2022-01-21 08:46 UTC, guqing requested changes

2022-01-21 08:46 UTC, guqing commented on core/src/main/java/run/halo/app/extensions/listener/PluginStateChangedListener.java
> +            Files.walkFileTree(path, new SimpleFileVisitor<Path>(){
@cooker 我认为没有必要去遍历目录 效率太低了 特别时目录很深时，在 deployment 模式下通过
```java
Path path = event.getPlugin().getPluginPath().toAbsolutePath();
```
已经可以获取到目录。
而在 development 模式下加载插件时使用的是 build/classes的内容因此实际是没有使用jar包的但是这里的静态文件加载还是依赖jar并且还解压了，我认为在开发模式下应该区别对待 可以直接通过插件类加载器获取到静态文件的目录直接复制到 halo的工作目录即可 无需使用 `new ZipFile(args)`处理

2022-01-21 08:50 UTC, cooker commented on core/src/main/java/run/halo/app/extensions/listener/PluginStateChangedListener.java
> +            Files.walkFileTree(path, new SimpleFileVisitor<Path>(){
👌

2022-02-26 13:21 UTC, guqing commented
hi @cooker 此PR是否还在继续

2022-04-05 14:29 UTC, guqing commented
此 PR 太久未活跃 我将关闭它 如有后续可以重新open

2022-04-05 14:29 UTC, closed without merging